# ===== build stage =====
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /workspace/app

# 先缓存依赖
COPY pom.xml .
RUN mvn -B -q -DskipTests dependency:go-offline

# 再拷源码并打包
COPY src src
RUN mvn -B -DskipTests package

# ===== run stage =====
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/app/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]