apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  01-create-appuser.sh: |
    #!/usr/bin/env bash
    set -euo pipefail
    echo "[init] creating app user and metrics collection..."

    mongosh --eval "
      // 1) create user.
      db = db.getSiblingDB('admin');
      try {
        db.createUser({
          user: '${MONGO_APP_USER}',
          pwd:  '${MONGO_APP_PASSWORD}',
          roles: [{ role: 'readWrite', db: '${MONGO_INITDB_DATABASE}' }]
        });
        print('[init] created app user');
      } catch(e) { print('[init] app user may already exist -> ' + e); }

      // 2) create collection
      db = db.getSiblingDB('${MONGO_INITDB_DATABASE}');
      if (!db.getCollectionNames().includes('metrics')) {
        db.createCollection('metrics');
        print('[init] created collection metrics');
      }

      // 3) apply index
      db.metrics.createIndex({ userId: 1, createdAt: -1 });
      db.metrics.createIndex({ userId: 1, kind: 1, createdAt: -1 });
      print('[init] indexes ensured');
    "