name: Build & Push Image
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} 
  TAG_SHA: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
    steps:
      # pull code
      - uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      
      # Build maven
      - name: Build Maven project
        run: mvn clean package -DskipTests
        working-directory: BackEnd

      # Optional
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Install DockerX 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build image and push to repo
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./BackEnd/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_LC }}:${{ env.TAG_SHA }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_LC }}:latest
          
      - name: Print image tag
        run: echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_LC }}:${{ env.TAG_SHA }}"
