CREATE TABLE IF NOT EXISTS mail_tokens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT        NOT NULL,
  token      VARCHAR(128)  NOT NULL UNIQUE,
  email      VARCHAR(255)  NOT NULL,
  username   VARCHAR(255)  NOT NULL,
  expires_at TIMESTAMP(6)  NOT NULL,
  used       BOOLEAN       NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_mail_tokens_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mail_token_user  ON mail_tokens(username);
CREATE INDEX IF NOT EXISTS idx_mail_token_email ON mail_tokens(email);