CREATE TABLE IF NOT EXISTS refresh_tokens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   VARCHAR(255)  NOT NULL,
  token      VARCHAR(255)  NOT NULL UNIQUE,
  device_id  VARCHAR(128)  NOT NULL,
  ip_address VARCHAR(45),
  created_at TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP(6)  NOT NULL,
  revoked    BOOLEAN       NOT NULL DEFAULT FALSE
);

ALTER TABLE refresh_tokens
  ADD CONSTRAINT uk_user_device UNIQUE (username, device_id);

CREATE INDEX IF NOT EXISTS idx_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_user  ON refresh_tokens(username);